ice:
  image: jonbrouse/ice:latest
  command: |
    -Djava.net.preferIPv4Stack=true
    -Djava.net.preferIPv4Addresses
    -Duser.timezone=${TIMEZONE}
    -Dice.s3AccessKeyId=${AWS_ACCESS_KEY_ID}
    -Dice.s3SecretKey=${AWS_SECRET_ACCESS_KEY}
    run-app
  volumes:
    - ./ice/assets/ice.properties:/opt/ice/src/java/ice.properties
nginx:
  image: jonbrouse/ice-proxy:latest
  ports:
    - "80:80"
  links:
    - ice:ice
